### ISSUE TITLE
recent update broke the addon

### ISSUE THREAD

**Issue by Joemacmalleus** [JereKuusela/valheim-infinity_hammer#48]
Was working fine - chose to hit the update, and now the addon has zero functionality :( - just posting to bring awareness to investigate :)

**Comment by xXRhaenyraXx** [comment]
It's currently like a game of roulette... have to have PlanBuild totally disabled, have to disable Infinity Hammer to use Marketplace NPC's ... Infinity Hammer is 50/50 chance I'll get indestructible or weathered/damaged... menu shows items selected that aren't selected or the menu just doesn't work at all... update a complete mess unfortunately !

**Comment by JereKuusela** [comment]
Latest version has some fixes. Also if you used the terrain tools, make sure to grab the new mod Infinify Tools.

**Comment by Joemacmalleus** [comment]
Thank you very much JereKuusela - I noticed the update and downloaded, now unfortunately the game wont load a server :/

I got one for a moment, noticed that the infinity hammer selections that normally show up in the build meny, still werent showing up, reloaded and isolated to use only this addon but now it wont load at all

**Comment by ging3rb3ardman** [comment]
First off, love this mod JereKuusela! it's phenomenal.

But I have to piggy-back on this issue as well.  Haven't had any of the GUI based tools working since update 1.44.  Just tried the new 1.45 and wasn't successful in recovering.  Have some limited functions working still in command I've found though.  To me the GUI building copy function is a life saver when it was working, same with hoe leveling, which I've found some functionality working via commands.

For context:
- I have Windows 10,

- Using R2modman for mod manager

- I have the following mods active:
- - BepInExPack by denikson
- -Server_devcommands by JereKuusela 
- -World_Edit_Commands by JereKuusela
- -Infinity_Hammer by JereKuusela
- -Comfy Gizmo by ComfyMods


These mods are installed but disabled:

- SmoothSave - by Smoothbrain
- Network - by Smoothbrain
- AntiCensorship by Smoothbrain
- NoAFKEvents by GemHunter1
- SimpleSort by Nexus
- MultiCraft by Maxi Mods
- ResourceUnloadOptimizer by Azumatt
- HideJoinCode by Azumatt
- FirstPersonMode by Azumatt
- FastLink by Azumatt (I did find this one messed with my GUI a bit)
- FastLink by Azumatt
- HideMe by Azumatt
- Circlet_Demister by Azumatt


Just trying to provide contextual help troubleshoot anything as I friggin love this mod.  I'll reply to things as soon as I see them if asked.

**Comment by ging3rb3ardman** [comment]
For my own due diligence I did uninstall all my disabled mods in this profile within R2modman, but unfortunately no dice.

**Comment by ging3rb3ardman** [comment]
> > For my own due diligence I did uninstall all my disabled mods in this profile within R2modman, but unfortunately no dice.
> 
> The simplest and only solution is to install the Infinity Tools mod. That's where the tools are now to make the base mod more lightweight.

Thank you.  This did help resolve the tools returning.

**Comment by Joemacmalleus** [comment]
I tried the above as instructed, it did indeed return the tool kit, however, now snapping no longer works with any item when using infinity hammer tools, it also removed the ability to use the area of effect terrain tools entirely (ala the Hoe) - just an fyi update.

Thanks for your hard work, looking forward to having it running smoothly again as i am half way through building the most detailed hogwarts Valheim has ever seeeeen!!!!
